[18.0][MIG] mail_restrict_follower_selection: Migration to 18.0
Kimkhoi3010/social pull request #2
Opened 2024-10-04 10:14 UTC by Kimkhoi3010

2024-10-07 09:18 UTC, thienvh332 commented
Please handle [this case](https://github.com/OCA/social/pull/1370#issuecomment-2312097275) as well.

2024-10-07 09:24 UTC, thienvh332 requested changes

2024-10-07 09:24 UTC, thienvh332 commented on mail_restrict_follower_selection/models/mail_thread.py
> +        # Chỉnh sửa để tương thích với cấu trúc `result` trong Odoo 18
Remove it
```suggestion

```

2024-10-15 05:26 UTC, closed without merging

2024-10-21 07:38 UTC, nilshamerlinck commented
@thienvh332 can you have a second look for final approval?